[project]
name = "genai-rag-ebooks"
version = "0.1.0"
description = "A chatbot project with RAG to chat with ebooks"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "js>=1.0",
    "langchain-core>=0.3.14",
    "langchain-openai>=0.2.4",
]
